### ISSUE TITLE
Validating work

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Staking#1]
- [x] Website page
- [x] Guides
- [x] Marketing plan

**Comment by johnniecosmos** [comment]
what is that about exactly?

**Comment by serejandmyself** [comment]
Still unfinished too = ) 

Mostly about creating a marketing plan for attracting delegations and what you can help with after that plan is in place

**Comment by johnniecosmos** [comment]
Create specific keywords on each blogpost for improving organic search rankings

**Comment by serejandmyself** [comment]
We are thinking on the same wave. I guess one of the only ways here is semantics
