### ISSUE TITLE
Citizen Cosmos Staking 

### ISSUE THREAD

**Issue by johnniecosmos** [citizen-cosmos/Staking#8]
## Create A dedicated Group to Citizen Cosmos Staking
- [ ]  Find TG Handle
- [ ] Make a Pinned Message with links to guides and page
- [ ] Administer the Group close to 24/7
- [ ] Atom & CYBER staking support

The diagram below still misses some of the actions that will be performed outside of the TG incl. producing content that will be polished and to a high standard, interlinking content, backlinking between Medium content and ensuring juice is passed on the website, my continuous presence on projects whose coins we validate. 

![mermaid-diagram-20201122093342](https://user-images.githubusercontent.com/71050153/99897875-e8afe680-2ca5-11eb-996b-15779fbb931f.png)

## Produce Staking Guides on TG Group Pinned
- [ ] Draft Articles
- [ ]  Link Existing Ones from Website
- [ ] Link Existing Ones from Medium

## Create Content on a Medium Dedicated Page back-linking to the Main Website
- [ ] Citizen Cosmos Staking Brand on Medium
- [ ] Link my Guides and Sergey's Guides
- [ ] Amend Articles in polished form using markdown/Medium style

## Explore High Reward/Inflation Chains for Staking Support & Services
- [ ] Secret Network
- [ ] Akash network

## Explore Means of Attracting Delegators
- [ ]  Offer soft/hard slash protection
- [ ] Have a large amount of self-staked tokens to increase trust in the brand
- [ ] Reduce the commission rate to a sustainable rate
- [ ] Provide Extensive overview of equipment and technology used
- [ ] Continuous presence/promotion on TG/Reddit groups of projects whose coins we validate

#### Cyber Staked: -----

**Comment by johnniecosmos** [comment]
some minor updates made and an infographic produced.

**Comment by serejandmyself** [comment]
Old issue, closed in favor of reorg
